import { useState } from "react";
import { ChevronRight } from "lucide-react";

const FAQS = [
  { q: "Does Aura store what I type?", a: "Yes — once linked to the backend, case details are persisted in DynamoDB behind the API, scoped to the logged-in user's role and ownership." },
  { q: "Can I use Aura for an emergency?", a: "No. Aura is not built for urgent or emergency situations. If a case is urgent, follow local emergency protocol right away." },
  { q: "Is this a diagnosis?", a: "No. Aura produces a ranked list of possibilities to consider, based on the details entered. A qualified clinician should confirm any actual diagnosis." },
  { q: "Where do the AI insights come from?", a: "They're generated by the backend's AI provider for the case — flags like risk factors, recorded allergies, or ruled-out concerns worth double-checking." },
  { q: "What powers the differential and exam suggestions?", a: "A Lambda-backed orchestrator behind API Gateway, configurable between a rule-based stub and a real model provider (see docs/AWS_CURRENT_STATE.md)." },
];

export default function KnowledgeView() {
  const [openFaq, setOpenFaq] = useState(0);
  return (
    <div className="knowledge-view">
      <h2>Knowledge base</h2>
      <p className="muted" style={{ marginBottom: 24 }}>Privacy, accuracy, and how Aura fits into a diagnostic workflow.</p>
      <div className="faq-list">
        {FAQS.map((f, i) => (
          <div className={"faq-item" + (openFaq === i ? " is-open" : "")} key={f.q}>
            <button className="faq-q" onClick={() => setOpenFaq(openFaq === i ? -1 : i)}>
              <span>{f.q}</span>
              <ChevronRight size={16} className="chev" />
            </button>
            <div className="faq-a-wrap">
              <div className="faq-a-inner"><p className="faq-a">{f.a}</p></div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
